setting:
  max: 50
  size: 9
info:
  reset:
    type: "reset"
    material: BLAZE_POWDER
    name: "스텟 초기화"
    color: e
    lore:
      itemlore:
        - "&f에메랄드를 소요하여"
        - "&f스텟을 &9&l초기화&r&f합니다."
      statup:
        - "&a소모 : 5,000EL"
    position: 8

  statpoint:
    type: "statpoint"
    material: BOOK
    name: "보유스텟"
    color: f
    lore:
      itemlore:
        - "&7자신만의         "
        - "&7스텟 투자로      "
        - "&7강해지세요 !     "
    position: 0

  statinfo1:
    type: "statinfo"
    material: STAINED_GLASS_PANE
    name: ""
    color: f
    itemcolor: 7
    lore:
      itemlore:
        - ""
    position: 1

  statinfo2:
    type: "statinfo"
    material: STAINED_GLASS_PANE
    name: ""
    color: f
    itemcolor: 7
    lore:
      itemlore:
        - ""
    position: 7


stats:
  vitality:
    type: "stat"
    material: APPLE
    name: "생명력"
    color: c
    lore:
      itemlore: "&a최대 체력 &f증가 스텟"
      statup:
        - "클릭 시 체력이 1 증가합니다."
      amount:
        health: 1
    position: 2
  attack:
    type: "stat"
    material: IRON_SWORD
    name: "공격력"
    color: c
    lore:
      itemlore: "&a공격력 &f증가 스텟"
      statup:
        - "클릭 시 해당 스텟을 올립니다"
      amount:
        damage: 0.25
        critical-damage: 0.1
    position: 3

  patience:
    type: "stat"
    material: TOTEM
    name: "인내"
    color: 6
    lore:
      itemlore: "방어력 증가 스텟"
      statup:
        - "클릭 시 해당 스텟을 올립니다"
      amount:
        defence: 2
        hungry: 2
    position: 4

  agility:
    type: "stat"
    material: FEATHER
    name: "민첩"
    color: b
    lore:
      itemlore: "&a이동속도 / 공격속도 &f증가 스텟"
      statup:
        - "클릭 시 해당 스텟을 올립니다"
    amount:
      speed: 0.005
      evasion: 0.2
    position: 5

  luck:
    type: "stat"
    material: NETHER_STAR
    name: "행운"
    color: a
    lore:
      itemlore: "&a회피 / 치명타 &f확률 증가 스텟"
      statup:
        - "클릭 시 해당 스텟을 올립니다"
    amount:
      luck: 3
    position: 6

  proficiency:
    type: "stat"
    material: EXP_BOTTLE
    name: "숙련도"
    color: e
    lore:
      itemlore: "&5경험치 획득 &f확률 증가 스텟"
      statup:
        - "클릭 시 해당 스텟을 올립니다"
    amount:
      exp-probability: 1
    position: 7

    magic-engineering:
      type: "stat"
      meterial: ENDER_PEARL
      name: "마법공학"
      color: d
      lore:
        itemlore: "&d희귀 인챈트 &f확률 증가 스텟"

      position: 8
